services:
  titirek:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: titirek
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PB_URL=${PB_URL:-http://localhost:8090}
      - PB_SUPERUSER_EMAIL=${PB_SUPERUSER_EMAIL}
      - PB_SUPERUSER_PASSWORD=${PB_SUPERUSER_PASSWORD}
      - APP_URL=${APP_URL:-http://localhost:3000}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    networks:
      - titirek-network

networks:
  titirek-network:
    driver: bridge
